language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/coveralls -v
